name: Deploy

on:
  push:
    branches: [ e2e-flow ]
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        default: none
        type: choice
        options: [major, minor, patch, none]
      modules:
        description: 'Comma-separated Maven modules to deploy (optional)'
        required: false
        default: ""

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.deploy.outputs.next_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Deploy pipeline
        id: deploy
        uses: CyborgCodeSyndicate/utilities/pipelines/deploy@e2e-flow
        with:
          server_ids: github-roa-libraries
          version_bump: ${{ inputs.version_bump || 'none' }}
          deploy_server_id: github-roa-libraries
          modules: ${{ inputs.modules }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_packages_user: ${{ secrets.GH_PACKAGES_USER }}
          github_packages_token: ${{ secrets.GH_PACKAGES_PAT }}

  e2e-tests:
    needs: deploy
    uses: CyborgCodeSyndicate/roa-example-projects/.github/workflows/e2e-tests.yml@e2e-flow
    with:
      snapshot_version: ${{ needs.deploy.outputs.next_version }}
    secrets:
      GH_PACKAGES_USER: ${{ secrets.GH_PACKAGES_USER }}
      GH_PACKAGES_PAT:  ${{ secrets.GH_PACKAGES_PAT }}